project:
  type: book
  output-dir: _full-book
book:
  chapters:
    - index.qmd

    - part: Семинарские занятия
      chapters:
        - seminar/1.qmd
        - seminar/2.qmd
        - seminar/3.qmd
        - seminar/4.qmd
        - seminar/5.qmd
        - seminar/6.qmd
        - seminar/7.qmd
        - seminar/8.qmd

    - part: Элементы теории
      chapters:
        - theory/crypto/random.qmd
        - theory/crypto/hash.qmd
        - theory/crypto/key-gen.qmd
        - theory/crypto/cypher.qmd


    - part: Контрольные работы

      chapters:
        - test/handout/1.qmd
        - test/handout/2.qmd
        - test/handout/3.qmd
        - test/handout/4.qmd
        - test/handout/5.qmd
        - test/handout/6.qmd
        - test/handout/7.qmd

    - part: Домашняя работа
      chapters:
        - lab/crypto/random/main.qmd
        - lab/crypto/hash/main.qmd
        - lab/crypto/key-gen/main.qmd
        - lab/crypto/cypher/symmetric/main.qmd
        - lab/crypto/cypher/asymmetric/main.qmd
        - lab/crypto/sign/main.qmd
        - lab/crypto/key-exchange/main.qmd
        - lab/crypto/cert/main.qmd

        - lab/access-control/ident/main.qmd
        - lab/access-control/authn/main.qmd
        - lab/access-control/authn/password-protection.qmd
        - lab/access-control/authz/model/main.qmd
        - lab/access-control/authz/windows/acl.qmd
        - lab/access-control/authz/windows/mic.qmd

        - lab/data-integrity/checksum/detection.qmd
        - lab/data-integrity/checksum/correction.qmd
        - lab/data-integrity/backup/main.qmd

        - lab/audit/code/main.qmd
        - lab/audit/event/main.qmd

        - lab/ddos/main.qmd
        - lab/social-engineering/main.qmd

    - references.qmd

  appendices:
    - lab/crypto/cypher/asymmetric/factorization.qmd
